# Generated by Django 4.2.7 on 2023-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_passengers', models.IntegerField()),
                ('fuel_consumption_per_minute', models.FloatField()),
                ('maximum_minutes_to_fly', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
