# Generated by Django 4.2.7 on 2023-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='fuel_tank_capacity_in_liters',
            field=models.FloatField(default=0.0),
        ),
    ]
