# Generated by Django 4.2.7 on 2023-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_airplane_fuel_tank_capacity_in_liters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='fuel_tank_capacity_in_liters',
            field=models.FloatField(),
        ),
    ]
